apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 721380728365.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest  # replace with your ECR URI
          ports:
            - containerPort: 5000
          env:
            - name: CAPSTONE_TEST
              valueFrom:
                secretKeyRef:
                  name: capstone-secret
                  key: CAPSTONE_TEST
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
